version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fruit-salad-rest-api
    environment:
      - DB_URL=${DB_URL:-jdbc:postgresql://fruit-salad-postgres:5432/fruit_salad_db}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - fruit-salad-network

  postgres:
    image: postgres:16.8
    environment:
      POSTGRES_DB: ${DB_NAME:-fruit_salad_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    container_name: fruit-salad-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - fruit-salad-network

volumes:
  db_data:

networks:
  fruit-salad-network:
    driver: bridge